services:
  _defaults:
    public: true
    autowire: true
    autoconfig: true

  SoulScripter\OrmTrait\Creator\PermissionBundleListener:
    autowire: true
    tags:
      - { name: doctrine.event_listener, event: prePersist }

  SoulScripter\OrmTrait\Updater\PermissionBundleListener:
    autowire: true
    tags:
      - { name: doctrine.event_listener, event: preUpdate }