services:
  _defaults:
    public: true
    autowire: true
    autoconfig: true

  Epubli\CreatorUpdaterBundle\Creator\PermissionBundleListener:
    autowire: true
    tags:
      - { name: doctrine.event_listener, event: prePersist }

  Epubli\CreatorUpdaterBundle\Updater\PermissionBundleListener:
    autowire: true
    tags:
      - { name: doctrine.event_listener, event: preUpdate }